### ISSUE TITLE
Right hemisphere delete

### ISSUE THREAD

**Issue by francopestilli** [brain-life/ui-tractview#11] opened 2017-12-01 16:14 UTC
There seems to be an issue with the current version deployed on brainlife.io when unselecting all tracts only the left-hemisphere tracts are removed from the visualization. All right hemisphere tracts stay. @soichih @stevengeeky

**Comment by soichih** [comment] 2017-12-01 16:55
This is a duplicate of issue #10 Steven will fix this.

**Comment by soichih** [comment] 2017-12-04 21:54
@stevengeeky Fixed this.

**Closed by soichih** 2017-12-04 21:54 UTC
